//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SYSDATAEntities : DbContext
    {
        public SYSDATAEntities()
            : base("name=SYSDATAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Owner> Owners { get; set; }
        public virtual DbSet<Parking_sessions> Parking_sessions { get; set; }
        public virtual DbSet<Parking> Parkings { get; set; }
        public virtual DbSet<Renter> Renters { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
